apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "momo-store.fullname" . }}-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: momo-backend
  template:
    metadata:
      labels:
        app: momo-backend
    spec:
      containers:
        - name: backend
          image: "{{ .Values.backend.image.repository }}:{{ .Values.backend.image.tag }}"
          ports:
            - containerPort: {{ .Values.backend.service.port }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "momo-store.fullname" . }}-backend
spec:
  ports:
    - port: {{ .Values.backend.service.port }}
      targetPort: {{ .Values.backend.service.port }}
  selector:
    app: momo-backend
