apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "momo-store.fullname" . }}-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: momo-frontend
  template:
    metadata:
      labels:
        app: momo-frontend
    spec:
      containers:
        - name: frontend
          image: "{{ .Values.frontend.image.repository }}:{{ .Values.frontend.image.tag }}"
          ports:
            - containerPort: {{ .Values.frontend.service.port }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "momo-store.fullname" . }}-frontend
spec:
  ports:
    - port: {{ .Values.frontend.service.port }}
      targetPort: {{ .Values.frontend.service.port }}
  selector:
    app: momo-frontend
